# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "myterraform-state-dev-bucket"
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "environments/uat/dynamodb/message-history-dev-table/terraform.tfstate"
    region         = "us-east-1"
  }
}
